{% set name = "constructs" %}
{% set version = "10.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/constructs-{{ version }}.tar.gz
  sha256: ce54724360fffe10bab27d8a081844eb81f5ace7d7c62c84b719c49f164d5307

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=70.0.0,<70.1.dev0
    - wheel >=0.42,<1.dev0
    - pip
  run:
    - python >=3.8
    - python-jsii >=1.102.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - constructs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/constructs
  summary: A programming model for composable configuration
  dev_url: https://github.com/aws/constructs
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
