{% set name = "constructs" %}
{% set version = "10.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/constructs-{{ version }}.tar.gz
  sha256: c0e90bb2b9c2782f292017820b91714321cb78393c8965c9362b0b624bfaf23b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70.0.0,<70.1.dev0
    - wheel >=0.42,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - python-jsii >=1.126.0,<2.0.0
    - publication >=0.0.3
    - typeguard ==2.13.3

test:
  imports:
    - constructs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/constructs
  summary: A programming model for composable configuration
  dev_url: https://github.com/aws/constructs
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
